In [27]:
# Step #1: Import necessary libraries
import pandas as pd
import requests

In [28]:
# URL of the JSON data
url = "https://c24215cec6c97b637db6-9c0895f07c3474f6636f95b6bf3db172.ssl.cf1.rackcdn.com/framed/~/media/multimedia/interactives/2015/college_value_added_prod/data/json/list.json"


# Fetch JSON data from URL
response = requests.get(url)
response.raise_for_status()
    
# Parse JSON data
data = response.json()

    
# Convert two_year college data to DataFrame
df = pd.DataFrame(data['two_year'])
df.shape

(4894, 14)

In [29]:
#1 Select relevant columns. In this step we are just bringing in specific columns that we need to, not the whole dataset with 
# other columns like latitude and longitudes
columns_to_keep = [
    'id', 'name', 'city', 'state', 'state_full', 
    'repay', 'sal', 'occ', 'salV', 'occV', 'repayV']


df = df[columns_to_keep]
print(df.shape)
print(df.head())

(4894, 11)
       id                              name         city  state  \
0  183099  NHTI-Concord's Community College      Concord   N.H.
1  226204                       Lee College      Baytown  Texas
2  176239     Pearl River Community College  Poplarville  Miss.
3  127884          Pueblo Community College       Pueblo  Colo.
4  189459               Briarcliffe College     Bethpage   N.Y.

      state_full  repay    sal   occ     salV     occV   repayV
0  New Hampshire   97.0  100.0  99.0  0.21690  0.07763  6.44894
1          Texas   28.0  100.0  77.0  0.20927  0.00435 -4.84821
2    Mississippi   58.0   99.0  52.0  0.20772 -0.01108 -1.45481
3       Colorado   27.0   99.0  28.0  0.19107 -0.02704 -4.97045
4       New York   40.0   99.0  54.0  0.18976 -0.00971 -3.31626

In [30]:
# 2: So the names in CSV are Standardized and wanted to make sure we use the same 
# standardizatoin here to join the data if required text case.

df['name'] = df['name'].str.title()
df['city'] = df['city'].str.title()
df.head()

,id,name,city,state,state_full,repay,sal,occ,salV,occV,repayV
0,183099,Nhti-Concord'S Community College,Concord,N.H.,New Hampshire,97.0,100.0,99.0,0.21690,0.07763,6.44894
1,226204,Lee College,Baytown,Texas,Texas,28.0,100.0,77.0,0.20927,0.00435,-4.84821
2,176239,Pearl River Community College,Poplarville,Miss.,Mississippi,58.0,99.0,52.0,0.20772,-0.01108,-1.45481
3,127884,Pueblo Community College,Pueblo,Colo.,Colorado,27.0,99.0,28.0,0.19107,-0.02704,-4.97045
4,189459,Briarcliffe College,Bethpage,N.Y.,New York,40.0,99.0,54.0,0.18976,-0.00971,-3.31626

In [31]:
# 3: Convert values from decimals to percentages
pct_columns = ['salV', 'occV', 'repayV']
df[pct_columns] = df[pct_columns] * 100
df[pct_columns] = df[pct_columns].applymap("{:.2f}%".format)
df.head()

/var/folders/cv/71w18t8n27b_81x9rhwkm1080000gq/T/ipykernel_77322/2506998601.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[pct_columns] = df[pct_columns].applymap("{:.2f}%".format)

,id,name,city,state,state_full,repay,sal,occ,salV,occV,repayV
0,183099,Nhti-Concord'S Community College,Concord,N.H.,New Hampshire,97.0,100.0,99.0,21.69%,7.76%,644.89%
1,226204,Lee College,Baytown,Texas,Texas,28.0,100.0,77.0,20.93%,0.43%,-484.82%
2,176239,Pearl River Community College,Poplarville,Miss.,Mississippi,58.0,99.0,52.0,20.77%,-1.11%,-145.48%
3,127884,Pueblo Community College,Pueblo,Colo.,Colorado,27.0,99.0,28.0,19.11%,-2.70%,-497.04%
4,189459,Briarcliffe College,Bethpage,N.Y.,New York,40.0,99.0,54.0,18.98%,-0.97%,-331.63%

In [32]:
# 4 Lets create groups based on salary or earning after degree is complete. 
df['Sal_range'] = pd.qcut(df['sal'],q=4,labels=['Low', 'Medium', 'High', 'Rich'])
df.head()

,id,name,city,state,state_full,repay,sal,occ,salV,occV,repayV,Sal_range
0,183099,Nhti-Concord'S Community College,Concord,N.H.,New Hampshire,97.0,100.0,99.0,21.69%,7.76%,644.89%,Rich
1,226204,Lee College,Baytown,Texas,Texas,28.0,100.0,77.0,20.93%,0.43%,-484.82%,Rich
2,176239,Pearl River Community College,Poplarville,Miss.,Mississippi,58.0,99.0,52.0,20.77%,-1.11%,-145.48%,Rich
3,127884,Pueblo Community College,Pueblo,Colo.,Colorado,27.0,99.0,28.0,19.11%,-2.70%,-497.04%,Rich
4,189459,Briarcliffe College,Bethpage,N.Y.,New York,40.0,99.0,54.0,18.98%,-0.97%,-331.63%,Rich

In [33]:
#5 Rename columns
df = df.rename(columns={
    'id': 'College ID',
    'name': 'Institution Name',
    'city': 'City',
    'state': 'State',
    'state_full': 'State Full Name',
    'repay': 'Repayment Rate',
    'sal': 'Salary Score',
    'occ': 'Occupational Score',
    'salV': 'Salary Value Added',
    'occV': 'Occupational Value Added',
    'repayV': 'Repayment Value Added',
    'Sal_range': 'Salary Range'
})

In [34]:
df.head()

,College ID,Institution Name,City,State,State Full Name,Repayment Rate,Salary Score,Occupational Score,Salary Value Added,Occupational Value Added,Repayment Value Added,Salary Range
0,183099,Nhti-Concord'S Community College,Concord,N.H.,New Hampshire,97.0,100.0,99.0,21.69%,7.76%,644.89%,Rich
1,226204,Lee College,Baytown,Texas,Texas,28.0,100.0,77.0,20.93%,0.43%,-484.82%,Rich
2,176239,Pearl River Community College,Poplarville,Miss.,Mississippi,58.0,99.0,52.0,20.77%,-1.11%,-145.48%,Rich
3,127884,Pueblo Community College,Pueblo,Colo.,Colorado,27.0,99.0,28.0,19.11%,-2.70%,-497.04%,Rich
4,189459,Briarcliffe College,Bethpage,N.Y.,New York,40.0,99.0,54.0,18.98%,-0.97%,-331.63%,Rich

# 1 paragraph of the ethical implications of data wrangling specific to your datasource and the steps you completed:

This time specifically when I was trying to get the data from the website, I had this feeling that am I doing right? The website was built pretty securely even though it was for public use. I literally have to dig up little to find the source as it was difficult to capture the data as is uing beautiful soup or even selenium and chrome driver. While going through all this excercise I relly felt if its ethical.  The changes made include selecting specific columns, standardizing institution names and cities, converting financial metrics to percentages, creating salary range categories, and renaming columns for clarity. While working with publicly available educational institution data, we must always consider regulatory implications, though this dataset appears to use aggregated institutional level data rather than personal identifiable information.The main risks from our transformations include potential bias in salary range categorization which could perpetuate socioeconomic stereotypes and the loss of nuance when standardizing names.
Key assumptions made during cleaning include treating all percentage conversions equally without considering regional cost of living differences and assuming standardized name cases are appropriate across all institutions.Also, assuming that the salary grouping applies same across all regions and does not factor in local cost of living.
While the data was acquired through public APIs, ethical considerations would be strengthened by documenting data provenance and ensuring transparent attribution.  To mitigate these implications, we should revise potentially biased category labels, maintain original institution names alongside standardized versions, add disclaimers about the limitations of percent based comparisons and salary based buckets.